### ISSUE TITLE
[Feature resquest] Portable Home Data

### ISSUE THREAD

**Issue by antrrax** [prateekmedia/appimagepool#10]
Add an option to choose how to run the AppImage:
with system user data, or with portable data

https://discourse.appimage.org/t/portable-configuration-data/105/13

To use the AppImage with portable Home data, just create a folder with the same name as the AppImage by adding the .home suffix, in the same directory as the AppImage file, or run the following command:
`./my_file.AppImage --appimage-portable-home`

like this:
`./appimagepool-x86_64.AppImage --appimage-portable-home`

**Comment by prateekmedia** [comment]
Do you mean to do this in downloaded appimages?

**Comment by antrrax** [comment]
On second thought, I think it can't be after the first run of the appImage, otherwise the files will be created in the system's Home.

It will be necessary to integrate the AppImageLaucher via the command line:
ail-cli integrate ./AppImage...
So it integrates AppImage without opening the program

**Comment by duke1995** [comment]
If this will be implemented, I'd propose to add the option to create both portable .home and .config directories.

See also the following question on Ask Ubuntu: [How does an AppImage persist settings between launches? - Ask Ubuntu](https://askubuntu.com/questions/1009888/how-does-an-appimage-persist-settings-between-launches/1010816#1010816)

**Comment by prateekmedia** [comment]
Thanks @duke1995 for that, I have added this in the latest commit you can test it here: https://github.com/prateekmedia/appimagepool/releases/continuous/
