### ISSUE TITLE
Unable to run appimage pool flatpak

### ISSUE THREAD

**Issue by synthsncats** [prateekmedia/appimagepool#12]
Hello,
I recently installed and tried running AppImagePool flatpak, but I get the following from the terminal:

`flatpak run io.github.prateekmedia.appimagepool
Gtk-Message: 15:47:40.967: Failed to load module "appmenu-gtk-module"
Gtk-Message: 15:47:40.968: Failed to load module "appmenu-gtk-module"
Gtk-Message: 15:47:40.968: Failed to load module "appmenu-gtk-module"
Gtk-Message: 15:47:41.076: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:47:41.078: Failed to load module "canberra-gtk-module"

** (appimagepool:2): WARNING **: 15:47:41.372: Failed to start Flutter renderer: No GL implementation is available
`
I've tried re-installing and using the "repair" command, but same problem.

**Comment by prateekmedia** [comment]
I think this should be fixed in v5, if you still face it I will reopen this issue. also if you are using flatpak I would suggest you to use AppImage instead.
