### ISSUE TITLE
Flatpak permissions wrong

### ISSUE THREAD

**Issue by 13hannes11** [prateekmedia/appimagepool#14]
When I first installed AppImagePool with flatpak it did not have a download button. In flatseal I noticed that the permissions were only for folder `~/Applications:create`. Changing this to `~/Applications` or allowing access to all user files fixed the problem.

**Comment by 13hannes11** [comment]
I don't quite get your question but I was checking the same app with these settings changed.

**Comment by prateekmedia** [comment]
I mean can you do the following:
1) reset permissions to default (:create)
2) reopen AppImage Pool and visit firefox AppImage
3) See if the download button appears

I think that this is not related to permissions but due to some AppImage not providing a download link (to AppImgeHub).

**Comment by 13hannes11** [comment]
Somehow I cannot reproduce the issue anymore I will therefore close it.
