### ISSUE TITLE
Not translated ?

### ISSUE THREAD

**Issue by Coeur-Noir** [prateekmedia/appimagepool#15]
Hi,

is it only available in english for the moment ?

Here on Ubuntu Budgie 20.04, appimagepool did not « take » my locale settings ( user and system wide, french ).

**Comment by prateekmedia** [comment]
I will make it localizable in the near future, Currently it's not.

**Comment by Vistaus** [comment]
> I will make it localizable in the near future, Currently it's not.

Cool! If you do, then I will provide the Dutch translation. :)

**Comment by Coeur-Noir** [comment]
Thanks for answer, Roma was not built in a day ;-)

**Comment by prateekmedia** [comment]
@Coeur-Noir  @Vistaus Translations are added :), You can translate the app to your preferred language and make a pull request, All translations will be located on https://github.com/prateekmedia/appimagepool/tree/main/lib/translations.
