### ISSUE TITLE
GLXBadFBConfig error while trying to run AppImage

### ISSUE THREAD

**Issue by jversusk** [prateekmedia/appimagepool#17]
I get this error while trying to run the AppImage on Linux Mint:
```
qt5ct: using qt5ct plugin

(appimagepool:10674): Gdk-ERROR **: 12:43:52.984: The program 'appimagepool' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 245 error_code 170 request_code 152 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```
Not sure what it means, wonder if it has something to do with my OpenGL version (2.1). If that is the case, would it be possible to add support for older OpenGL versions?

**Comment by prateekmedia** [comment]
Can you try the flatpak version, Also are you on a VM or a real device?

**Comment by jversusk** [comment]
Not a VM. The flatpak version would require additional ~800MB and this drive is low on free space, which is why I haven't tried it. But I do have Linux (Manjaro) installed on an external HDD as well, will try (appimage or flatpak) on that and post an update.

**Comment by jversusk** [comment]
The appimage works under Manjaro on the same device, dunno why it doesn't work under Linux Mint (version 20 Cinnamon edition). I've been thinking of switching to Manjaro anyway, so feel free to close this issue if it doesn't affect other users.
