### ISSUE TITLE
No Icon is shown for AppImage

### ISSUE THREAD

**Issue by atul-chaudhary** [prateekmedia/appimagepool#23]
I'm able to run appImage successfully, but the problem is it doesnt have any icon associated with it,[running appImagepool show blank/no icon in taskbar] I check the files you are copying the icon, and also it pesent in .desktop file, then why it is not shown while running.

**Comment by prateekmedia** [comment]
You have to install the app using appimagelauncher in order to show the icon correctly.

Install appimagelauncher
Double click the downloaded AppImage
Click integrate and run and done

**Comment by atul-chaudhary** [comment]
Hi @prateekmedia, through appImage launcher tool icon is present in show all application section, but as soon as we run the application still no icon is shown in the taskbar, facing same issue with my own flutter application.

**Comment by prateekmedia** [comment]
@atul-chaudhary Can you try restarting your PC if you have integrated the appimage to your system.

**Comment by atul-chaudhary** [comment]
Hi @prateekmedia thanks for quick response, restarting the system solved the problem. in case of appImagePool app.

But in my case [my own flutter project] icon is shown in show all application section but not on taskbar I'm using svg  image as icon.
