### ISSUE TITLE
Blank grey screen on "Etcher" install

### ISSUE THREAD

**Issue by Lexolas** [prateekmedia/appimagepool#24]
When i try to install "Etcher" i get a blank grey screen and nothing happens....
![Screenshot from 2021-12-22 18-20-10](https://user-images.githubusercontent.com/12045801/147131087-47ffd3d8-bdf2-477b-9ed6-5ea5f9e4b406.png)

But other Apps (e.g. Blender) work well!!

My System:
Arch Linux (5.10.87-1-lts) with Gnome 41.2
AppImage Pool (4.9.0) installed from Flathub
Problem exists on Wayland and X11

**Comment by prateekmedia** [comment]
Maybe a problem with etcher AppImage, I will try installing it and see if it's the same, then you can report this to Etcher appimage developers.

**Comment by Lexolas** [comment]
Thank you for your reply. I wasn't very precise in my issue-description: I don't think it is the AppImage, because the error already occurs when fetching the available releases from github (the url is correct though).

**Comment by prateekmedia** [comment]
@Lexolas Please check the nightly build of this to check if the issue is fixed for you or not.
