### ISSUE TITLE
Unable to run appimagepool on arch linux Kde 

### ISSUE THREAD

**Issue by thomasongwae** [prateekmedia/appimagepool#30]
[thomasongwae@spiderX Downloads]$ ./appimagepool-x86_64.AppImage
flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1196)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1017)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:535)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:948)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:137)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
Segmentation fault (core dumped)

**Comment by magnus-ISU** [comment]
Hmm. I get the same `Unsupported Operation` crap, but it doesn't segfault.

```
flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1196)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1017)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:535)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:948)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:137)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
```

(then it runs fine)

**Comment by prateekmedia** [comment]
@magnus-ISU That's related to svg , some svg formats are not supported yet.

**Comment by prateekmedia** [comment]
@thomasongwae Can you run again and see if this persists or it's a random one.

If persists post your neofetch output.

**Comment by thomasongwae** [comment]
> @thomasongwae Can you run again and see if this persists or it's a random one.
> 
> If persists post your neofetch output.

it persists
i have attached the neofetch output as a screenshot using the link below
https://disk.yandex.com/i/3TC5CwPxPly9jw

**Comment by prateekmedia** [comment]
I would suggest you to report this at the [official flutter sdk](https://github.com/flutter/flutter) as it is related to that, mostly this occurs due to OpenGL not present or system having very old hardware or very old graphics card.
