### ISSUE TITLE
Highlight (un-)official AppImages - more trust in AppImages

### ISSUE THREAD

**Issue by webmanufaktur** [prateekmedia/appimagepool#32]
While I appreciate the work each and everyone does, who creates an AppImage for a programm/app/software some or all of us use. I'd like to see and highlight those AppImages that are either **NOT OFFICIAL** or from **OFFICIAL** sources.

Sure we can look into those AppImages, investigate, look up and so on but... NO.
That's nothing a (new) user would, could or should do.

AppImages are awesome and maybe even one of the better options to install software but without a clear indicator if an AppImage was created by official sources or by a 3rd-party may hold some risks.

In regards to AppImagePool this feature (highlighting either official or non-official AppImages, better both in some kind) could benefit all users, the whole community and would build trust in AppImagePool and AppImages in general as it clearly indicates from which source an image comes.

**Comment by prateekmedia** [comment]
Sure, but there isn't an API available for that, So either all or none are official as we cannot detect it.

**Comment by dezbracaty** [comment]
> 

Sorry I have a different point of view . As we know , the software user use on ubuntu platform are from three or four ways , such like github developer (open source) , software home (such like edge browser , unopen source) ,and other ways .
For appimage, it can be roughly divided into several types
1 Appimage released by the developer (open source and not open source)
2 Appimage (open source and not open source) made according to the deb announced by the developer
3 Appimage made according to the deb published on the official software website (most of them are not open source) 

Therefore, it can be roughly classified into whether it is from github and whether it is open source.

**Comment by prateekmedia** [comment]
@webmanufaktur @dezbracaty Although I appreciate your feedback but sadly I cannot do anything regarding that as this app is just appimagehub's frontend with additional features.

What I do suggest is to create an issue directly at appimagehub's repo, that way we can use that data.
https://github.com/AppImage/appimage.github.io/
