### ISSUE TITLE
Unable to run AppImage Pool on Debian 11

### ISSUE THREAD

**Issue by midvok** [prateekmedia/appimagepool#37]
I run Debian 11 with Gnome and Wayland.
I'm unable to run the AppImage Pool either using flatpak nor appimage pool and getting this error:

```shell
$ flatpak run io.github.prateekmedia.appimagepool
** (appimagepool:2): WARNING **: 15:36:46.681: Failed to start Flutter renderer: Unable to create a GL context
```

However, I was able to run the AppImage Pool when logged to Gnome in X mode, but in that case its UI does not respect my system theme but having some bright "default" theme.

**Comment by prateekmedia** [comment]
Wayland is not tested by me so I cannot comment on it right now.

**Comment by radasbona** [comment]
I have the also an Issue with Bullseye.
I use x.org and a Mate Desktop.

I started AI Pool as an Appimage with a crash after 4-5 seconds. 
Here is the terminal output:

flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1196)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1017)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:535)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:948)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:137)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by prateekmedia** [comment]
@radasbona The terminal output is normal as it shows the errors with Svg packages that everyone faces.

I dont know why your app is crashing.

**Comment by radasbona** [comment]
The flatpak is even worse. 
It freezes the entire system at the same time. 

Too bad, I thought the terminal output would help you. 

Does the tool use hardware acceleration? I often had problems with that. Among other things with the current Firefox.


Am 14. Januar 2022 13:53:10 MEZ schrieb Prateek SU ***@***.***>:
***@***.*** The terminal output is normal as it shows the errors with

**Comment by prateekmedia** [comment]
@radasbona Could you send me your neofetch output?

**Comment by radasbona** [comment]
Sure. It's old - i know. ;-) 
[neofetch.txt](https://github.com/prateekmedia/appimagepool/files/7872784/neofetch.txt)

**Comment by pacnica** [comment]
I have the also an Issue with Hirsuite with KDE
I use x.org and a Kwin Desktop.

With the app launcher appimage tool start, but few seconds it close.

Then I reinstall with
 
`flatpak install --reinstall appimagetool`

Dont work, else.

I try with command line 

`flatpak run io.github.prateekmedia.appimagepool.flatpakref` 

"Not found"


the I use the same in the app

`/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=appimagepool --file-forwarding io.github.prateekmedia.appimagepool @@u %u @@
`

This is terminal output:

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/pacnica/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No existe el fichero o el directorio, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous  [#suspension>](url)
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/pacnica/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No existe el fichero o el directorio, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/pacnica/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No existe el fichero o el directorio, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _RawDecoratedWindowButtonState.getTheme (package:window_decorations/src/decorated_button.dart:159)
<asynchronous suspension>

[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FileSystemException: Cannot open file, path = '/home/pacnica/.var/app/io.github.prateekmedia.appimagepool/config/dconf/user' (OS Error: No existe el fichero o el directorio, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356)
#1      _rootRunUnary (dart:async/zone.dart:1434)
<asynchronous suspension>
#2      GVariantDatabase._loadRootTable (package:gsettings/src/gvariant_database.dart:30)
<asynchronous suspension>
#3      GVariantDatabase.lookup (package:gsettings/src/gvariant_database.dart:20)
<asynchronous suspension>
#4      DConfClient.read (package:gsettings/src/dconf_client.dart:85)
<asynchronous suspension>
#5      GSettings.get (package:gsettings/src/gsettings.dart:94)
<asynchronous suspension>
#6      _AdwHeaderBarState.initState.<anonymous closure> (package:libadwaita/src/widgets/adw/header_bar.dart:242)
<asynchronous suspension>

flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1196)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1017)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1177)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:535)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:948)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:137)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'
nouveau: kernel rejected pushbuf: No existe el fichero o el directorio
nouveau: ch12: krec 0 pushes 2 bufs 30 relocs 0
nouveau: ch12: buf 00000000 00000002 00000004 00000004 00000000

Here data with inxi -b output:

[datospc.txt](https://github.com/prateekmedia/appimagepool/files/7963433/datospc.txt)

**Comment by prateekmedia** [comment]
I would suggest you to report this at the [official flutter sdk](https://github.com/flutter/flutter) as it is related to that, mostly this occurs due to OpenGL not present or system having very old hardware or very old graphics card.
