### ISSUE TITLE
Opening error

### ISSUE THREAD

**Issue by AgostinoA** [prateekmedia/appimagepool#41]
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(53)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed

**Comment by prateekmedia** [comment]
@AgostinoA Could you send me your `neofetch` output?

**Comment by prateekmedia** [comment]
I would suggest you to report this at the [official flutter sdk](https://github.com/flutter/flutter) as it is related to that, mostly this occurs due to OpenGL not present or system having very old hardware or very old graphics card.
