### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by SilverMarcs** [prateekmedia/appimagepool#46]
Would it be possible in flutter to make window corners rounded, following Gnome HIG?

**Comment by prateekmedia** [comment]
https://github.com/bitsdojo/bitsdojo_window/issues/97#issuecomment-894135319

**Comment by SilverMarcs** [comment]
Cool. Btw would it be possible for the app to detect which window control buttons are enabled system-wide, instead of dispaying all of them always? How about smooth scrolling?

**Comment by prateekmedia** [comment]
> Cool. Btw would it be possible for the app to detect which window control buttons are enabled system-wide, instead of dispaying all of them always?

It is already detected, based on the gtk preferences, you can check it by disabling some buttons from gnome tweaks.

> How about smooth scrolling?

I don't know about it.

**Comment by prateekmedia** [comment]
Merged with #11
