### ISSUE TITLE
Missing appimages

### ISSUE THREAD

**Issue by danrobi11** [prateekmedia/appimagepool#5]
Hi I've noticed that [FreeTube](https://github.com/FreeTubeApp/FreeTube) and [ImageMagick](https://github.com/ImageMagick/ImageMagick) are not available through appimagepool. Both projects maintainer does provide an appimage. So I was wondering who do I need to contact about this.

**Comment by prateekmedia** [comment]
FreeTube => https://github.com/AppImage/appimage.github.io/pull/629
ImageMagick => https://github.com/AppImage/appimage.github.io/pull/456

**Comment by prateekmedia** [comment]
Closing as not related to this software.
