### ISSUE TITLE
Within 1/4 of a second it closes!

### ISSUE THREAD

**Issue by joellapointe1717** [prateekmedia/appimagepool#50]
I tried to use the software in Linux Mint 20.3. I installed it with the 3 ways :
- Flatpak
- Appimage
- Appimage continuous
All of them has the same problem : 
- I run the program, 
- I'm able to see the interface, 
- within 1/4 of a second it closes!

**Comment by prateekmedia** [comment]
Any logs? Try running from terminal for logs.

**Comment by prateekmedia** [comment]
Closing due to lack of response, Most of the time it also depends on hardware if it's too old this app won't work.
