### ISSUE TITLE
Audacity listed in the Video section

### ISSUE THREAD

**Issue by JoaoGFarias** [prateekmedia/appimagepool#52]
On the version 4.9.9, Audacity is listed on the Video section, although it is an audio-focused program.

![image](https://user-images.githubusercontent.com/1585655/159125258-56885340-8904-4681-ae3b-29d0431fd897.png)

**Comment by prateekmedia** [comment]
You are right, It was in AudioVideo category in the upstream repository so I listed it in Video page. Looks like I should create a new Multimedia page for this.

**Comment by prateekmedia** [comment]
I have created Multimedia category to fix this, this is how it will look in v5 till then you can test nightly appimage from README
![image](https://user-images.githubusercontent.com/41370460/159135534-46bf46f2-915a-482b-8b54-f62414b94c47.png)

**Comment by prateekmedia** [comment]
Fixed in v5!
