### ISSUE TITLE
Incorrect fallback locale

### ISSUE THREAD

**Issue by 154pinkchairs** [prateekmedia/appimagepool#53]
My locale was set to Polish and additionally I had English enabled in Gnome settings as a secondary language. When I started the app, all strings were in Arabic, so I had to change to English, which necessitated logging out, in order to use the app. 

I would be eager to contribute if a **Weblate** translation project was set up for Polish. In the meantime it would be appreciated if the app worked in accordance to the locales set in the system, not as if it randomly chose the first available one.

**Comment by tr1p0p** [comment]
Yeah same, in french. Not very usable then.

**Comment by prateekmedia** [comment]
I will report this to the flutter repository as I have no control over it.

**Comment by prateekmedia** [comment]
Weblate => https://hosted.weblate.org/projects/appimagepool/

**Comment by prateekmedia** [comment]
Anyone facing this can try the new nightly version
