### ISSUE TITLE
Disable automatic scrolling of screenshots

### ISSUE THREAD

**Issue by alexkdeveloper** [prateekmedia/appimagepool#60]
It is better to do manual scrolling of screenshots. Or at least make the screenshot gallery scroll only if it contains more than one item. Now, for some reason, screenshots scroll even if there is only one component in the gallery. You can also increase the screenshot display time. It would be nice to additionally disable scrolling when hovering the mouse cursor over the screenshot.

**Comment by prateekmedia** [comment]
Fixed in the nightly version.
