### ISSUE TITLE
Deleting an integrated appimage does not disintegrate before deletion

### ISSUE THREAD

**Issue by HimDek** [prateekmedia/appimagepool#61]
When an integrated appimage is deleted from the Installed list, it is not disintegrated before deletion because of which its application menu entry remains even if the app itself is removed. Desired behaviour would be that the app is disintegrated before deletion.

### Steps to produce:
* Download any appimage from appimagepool.
* Go to the Installed list.
* Find the downloaded appimage entry and click the corresponding integrate button.
* Delete the integrated appimage.

### Observed Behaviour:
The application menu entry of the appimage remains.

### Expected behaviour:
The appication menu entry should be removed and any other integrations or changes the integrate button does should be reversed.

**Comment by prateekmedia** [comment]
Fixed, check nightly version from readme to test.
