### ISSUE TITLE
NOT working on Kubuntu 22.04

### ISSUE THREAD

**Issue by pigeonskiller** [prateekmedia/appimagepool#66]
Hi, sorry to inform you it does NOT work Kubuntu 22.04.

Same behavior both with double click and from terminal.

Here the log from terminal:

./appimagepool-5.0.0-x86_64.AppImage
[FATAL:flutter/shell/gpu/gpu_surface_gl_delegate.cc(53)] Check failed: gl_version_string. The GL proc resolver's glGetString(GL_VERSION) failed
Aborted (core dumped)

Hope you solve the bug soon. Thanks for the app.

**Comment by prateekmedia** [comment]
Probably you have an old processor or old gpu, did you?

**Comment by pigeonskiller** [comment]
Yes, my processor and GPU are old but drivers are updated tot the latest version.
The question is: why does the app need GL? To show icons previews?
Older versions of the app worked fine on the same hardware...

**Comment by prateekmedia** [comment]
What was the last version that worked for you?

**Comment by pigeonskiller** [comment]
Sorry, my mistake.
It worked on Kubuntu 21.10 with the same old hardware...
I don't remember exactly the working version on the previous distro, anyway now I'm on 22.04 and I cannot check it anymore.

**Comment by prateekmedia** [comment]
I would suggest you to report this at the [official flutter sdk](https://github.com/flutter/flutter) as it is related to that, mostly this occurs due to OpenGL not present or system having very old hardware or very old graphics card.
