### ISSUE TITLE
System Window Decoration

### ISSUE THREAD

**Issue by tio-trom** [prateekmedia/appimagepool#74]
Is it possible to please add and enable a system window decoration? Without it we lose functionality (the right click that allows users to move windows on different workspaces and so much more) + usability (does not respect the system's theme). Thanks!

**Comment by prateekmedia** [comment]
Added the first one, will not add the second one as we strictly follow libadwatia's guidelines as of now, You can check the nightly version in README to test this.

**Comment by prateekmedia** [comment]
This issue is a duplicate of #11 and #47

**Comment by tio-trom** [comment]
Thank you!
