### ISSUE TITLE
[Package Reqest] Add RemNote

### ISSUE THREAD

**Issue by LMech** [prateekmedia/appimagepool#86]
[RemNote](https://www.remnote.com/download) is a helpful cross-platform note-taking app, I would be thrilled if it's added to the existing packages.

I have a background in coding and GitHub, if there is a guide to add it and maintain it myself let me know.

**Comment by prateekmedia** [comment]
Please visit https://github.com/AppImage/appimage.github.io for submission of appimages, thanks!

**Comment by LMech** [comment]
I read the instructions, but the application is commercial, so I think it won't be picked automatically.

Either way, I will try.
