### ISSUE TITLE
Feature Request: Create a .desktop launcher for applications downloaded with AppImage Pool

### ISSUE THREAD

**Issue by damies13** [prateekmedia/appimagepool#92]
Hi,

**Background** 
I'm using Ubuntu 22.04.1 LTS, but I guess this apply's for anyone using Gnome.

I downloaded an application using AppImage Pool (installed as a flatpak from flathub, using the Gnome Software), in my case the application was balena Etcher.

After installing the only way I could launch Etcher was from AppImage Pool's installed tab as the app wasn't showing up in the "Show Applications" screen, fortunately i found all I needed to do was create a .desktop file for the AppImage application and now it works. For more beginner users this would be quite confusing.

**Feature Request**
I would like to request as a new feature for AppImage Pool, that when an AppImage is downloaded and installed with AppImage Pool, that the .desktop file is automatically created. 

**Additional Information**
Here is a link to the instructions I followed, the answer marked as the best answer is what worked for me.
https://askubuntu.com/questions/1403802/how-to-add-appimages-to-taskbar-and-applications-list

Also for reference here is the file I created that resolved the issue for me: *~/.local/share/applications/Etcher.desktop*

```
[Desktop Entry]
Name=Etcher
Exec=/home/dave/Applications/balenaEtcher-1.15.5-x64.AppImage %f
Type=Application

```

I would be nice to have icons and relevant file associations etc. but really that's just polish on this feature request.

**Comment by prateekmedia** [comment]
If you click on Integrate App Image button it will do the exact same thing

**Comment by damies13** [comment]
Thanks for the info, where do I find the Integrate App Image button?

![Screenshot from 2023-02-14 12-28-11](https://user-images.githubusercontent.com/15232871/218623324-eb41807c-4b2f-4bda-b8dd-873269c5c3d7.png)

Dave.

**Comment by prateekmedia** [comment]
in the top we have Installed tab.
