### ISSUE TITLE
Update changed language to Arabic

### ISSUE THREAD

**Issue by Rathmox** [prateekmedia/appimagepool#93]
I just updated to version 5.0.0 from flathub and the app language got changed to Arabic instead of my system language

**Comment by yodatak** [comment]
I just report it to the flathub issue too https://github.com/flathub/io.github.prateekmedia.appimagepool/issues/12

**Comment by yodatak** [comment]
same here too https://github.com/prateekmedia/appimagepool/issues/64

**Comment by prateekmedia** [comment]
fixed by release 5.1.0, will update on flathub soon
