### ISSUE TITLE
Wrong lenguage by default (even different alphabet)

### ISSUE THREAD

**Issue by guiopen** [prateekmedia/appimagepool#95]
Tested on the flatpak version of the app on fedora silverblue

The app's default language is some (Arabic?) language I don't recognize. My system is in brazilian portuguese, so its expected from the app to be in portuguese or english if portuguese is not available. Aside from that, amazing app, beatiful and super fluid.

![Captura de tela de 2023-03-01 00-17-23](https://user-images.githubusercontent.com/94094527/222036642-cc8147b3-6b76-45af-9218-0eaf49e316af.png)

**Comment by prateekmedia** [comment]
Try again in few hours

**Comment by prateekmedia** [comment]
Just updated flatpak
