### ISSUE TITLE
Can not change the default application folder (Ubuntu 22.04 - appimagepool v.5.1.0)

### ISSUE THREAD

**Issue by f-mc2** [prateekmedia/appimagepool#98]
Basically, the title. I just downloaded the appimage of appimagepool, and I am not able to change the default application folder (nor any other folders in the preferences menu). I click but nothing happens. 
I tried to remove the file, remove the folder I find in .local/share, but still nothing happens.
I apologize in advance if this issue is trivial or misplaced.

**Comment by prateekmedia** [comment]
can you launch appimagepool from terminal and see if there are any errors?

**Comment by f-mc2** [comment]
I get the following:

flutter: Unsupported operation: Unsupported clipPath child g
flutter: #0      debugPrintStack (package:flutter/src/foundation/assertions.dart:1209)
flutter: #1      FlutterError.dumpErrorToConsole (package:flutter/src/foundation/assertions.dart:1028)
flutter: #2      FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1189)
flutter: #3      _Elements.clipPath (package:flutter_svg/src/svg/parser_state.dart:491)
flutter: #4      SvgParserState.parse (package:flutter_svg/src/svg/parser_state.dart:887)
flutter: <asynchronous suspension>
flutter: #5      SvgParser.parse (package:flutter_svg/parser.dart:27)
flutter: <asynchronous suspension>
flutter: #6      Svg.fromSvgString (package:flutter_svg/svg.dart:139)
flutter: <asynchronous suspension>
flutter: #7      Svg.svgPictureDecoder (package:flutter_svg/svg.dart:57)
flutter: <asynchronous suspension>
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

**Comment by prateekmedia** [comment]
Did you tried clicking on change folder button when you saw these logs? If not please click on that and tell me what errors were there

**Comment by f-mc2** [comment]
This is what I get:

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Couldn't find the executable zenity in the path.
#0      isExecutableOnPath (package:file_picker/src/utils.dart:60)
<asynchronous suspension>
#1      FilePickerLinux._getPathToExecutable (package:file_picker/src/linux/file_picker_linux.dart:119)
<asynchronous suspension>
#2      FilePickerLinux.getDirectoryPath (package:file_picker/src/linux/file_picker_linux.dart:64)
<asynchronous suspension>
#3      PrefsDialog.build.browseFolder (package:appimagepool/src/features/home/presentation/home/prefs_dialog.dart:28)
<asynchronous suspension>

**Comment by prateekmedia** [comment]
You are missing zenity on your system, I will try to include that in future on the AppImage itself but just install it from apt for now.

**Comment by f-mc2** [comment]
OK, this was so simple. Thank you very much for the help, and sorry for the silly request.

**Comment by prateekmedia** [comment]
np 😃
